# Generated by Django 5.0.2 on 2024-03-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_properties_description_and_more'),
    ]

    operations = [
    ]
