# Generated by Django 5.0.2 on 2024-03-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20240307_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='added_status',
            field=models.CharField(default='just now', max_length=25),
        ),
        migrations.AddField(
            model_name='properties',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='properties',
            name='balcony',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='properties',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='properties',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='properties',
            name='brokerage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='properties',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='properties',
            name='parking',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='properties',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='properties',
            name='price_per_sqft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='properties',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
