# Generated by Django 5.0.2 on 2024-03-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_properties_added_status_properties_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='img1',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='img2',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='img3',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='img4',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='properties',
            name='img5',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
