# Generated by Django 5.0.2 on 2024-03-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_properties_img1_properties_img2_properties_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='properties',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
